### ISSUE TITLE
Grep icon

### ISSUE THREAD

**Issue by Mr-Administrator** [dnGrep/dnGrep.github.io#3]
Hello, I have cleaned up dnGrep's icon, as well as increased the color saturation and contrast a tad bit. I uploaded the files on my fork of dnGrep, if you are interested in using the improved icon. Not sure if I am doing the right thing messaging you like this in a public issue, my apologies if not. 

https://github.com/Mr-Administrator/dnGrep

-Mr.Administrator

**Comment by JVimes** [comment]
@Mr-Administrator Please post the request at https://github.com/dnGrep/dnGrep/issues and attach the specific icon files. Then the devs can take a look. Thanks!

**Comment by Mr-Administrator** [comment]
@JVimes Will do!

**Comment by Mr-Administrator** [comment]
@JVimes Will do!

**Comment by doug24** [comment]
The images and icons have been updated, thank-you!
